# Generated by Django 5.2.4 on 2025-08-04 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_click_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='movie',
            new_name='post',
        ),
    ]
